  fixed PY-3853 Error in utrunner.py when running unit tests  