  Fixed bug in checking for sequence instead of iterable in '*args' (PY-5057)  