  Exception when debugging fork_exec without attaching to process (PY-16690)  Create a separate warning function for _posixsubprocess module  