  proper fix for PY-12052 Can't run django tests with nosetests because of `nose_utils` not found.  