  PY-2880: Django: provide completion for context_object_name value in django template * test added * fixture:complete() is reenterable now  